runtime: python27
api_version: 1
version: 1
threadsafe: true

handlers:

- script: api.app
  url: /api/.*

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
